### ISSUE TITLE
Callback after "Get Access Token" does not work in browser

### ISSUE THREAD

**Issue by BenjaminJohn** [GuidoPreite/DRB#17] opened 2023-06-07 09:43 UTC
Hi,

I use the Dataverse REST Builder in version 1.0.0.43 (currently the latest release) in Edge and Chrome.

The steps I do:
1. I enter a CE URL or select one from the recent environment list
2. I press the "Get Access Token" button and get redirected to login.microsoftonline.com
3. I enter my credentials or choose one from the existing list
4. I get redirected to https://callbackurl/#access_token=eyJ0_TOKEN_GOES_ON_&_ON__&token_type=Bearer&expires_in=5038&session_state=a4370a35-0697-41c6-a391-744196241974
5. Here it ends. The REST Builder does not open, and the browser says that the page is not reachable and that I should check for typos in the URL. The browser also shows the message "DNS_PROBE_FINISHED_NXDOMAIN"

I already checked on my side:
- Different browsers (Edge, Chrome) on my local machine (MacOS) with different Power Plattform Tenants
- Edge on my local VM (Windows 11 ARM)
- Chrome on an Azure VM (Windows Server), to check if it is a local network issue

Best regards
Ben

**Comment by GuidoPreite** [comment] 2023-06-07 09:53
Hi @BenjaminJohn,
thanks for reporting it. I can confirm it's not working also from my side.
I will need to check if is a problem of the url or something has changed inside the extension logic (the listener of the url).
Meanwhile you can use the other versions (Managed Solution or XrmToolBox, probably your default machine is a Mac so I understand why you use the browser version).
I am not able to provide an estimate because if the problem is of the extension logic there is a risk that is not fixable at all.

**Comment by GuidoPreite** [comment] 2023-06-07 13:58
Hi @BenjaminJohn,
I applied a fix to the code and locally the extensions work in my browsers (Chrome and Edge both on Windows).
I submitted a new version (1.0.0.44) in both stores, hopefully they publish it soon. After they publish I will update this issue with the result.

**Comment by GuidoPreite** [comment] 2023-06-07 18:11
Hi @BenjaminJohn,
Chrome Web Store (https://chrome.google.com/webstore/detail/dataverse-rest-builder/ioajdaokkkgjehbpiogakecdifaeaeho) already updated the version and you can download the new one (if the extension doesn't get updated, remove and add it again).
Let me know if this solve your problem, Edge version will be published in the next days.

**Comment by irah2008** [comment] 2023-06-08 03:11
@GuidoPreite  Awesome, the issue is fixed and works as expected from chrome web store. For time being chrome add-on can be installed in edge and works as expected.

Thanks for the swift response

**Comment by BenjaminJohn** [comment] 2023-06-08 11:09
Version 1.0.0.44 from Chrome Web Store works for me too on Chrome and Edge.

Thank you for the outstanding support for this issue and the community itself.

**Comment by GuidoPreite** [comment] 2023-06-08 11:11
thanks @BenjaminJohn for reporting that works for you now.
I will keep this issue opened until the Edge version is updated.

**Comment by GuidoPreite** [comment] 2023-06-13 09:55
Edge Add-ons website listed the new version.
Thanks again @BenjaminJohn for reporting this problem.
I close the issue.

**Closed as completed by GuidoPreite** 2023-06-13 09:55 UTC
Labels: bug, good first issue
